### PR TITLE
Add newlines to sentences for proper view

### PR DESCRIPTION
**Pull request by src4026**
I am pretty sure these changes have to be translated, isn't it? I have made the changes as per an issue opened about the Moderators list not being properly visible, and my issue that was caused by a thick font. AFAIK, these changes would probably work for all font types. Unfortunately, I don't know how to test this change in-game. If anyone could help me with it, I would be grateful :)

### CODE REVIEW

**Comment by src4026** [comment]
I will be looking at editing the translations later. For now, this is not a completed PR.

**Comment by src4026** [comment]
@LoneWolfHT , I was wondering whether making the formspec wider be a solution rather than making newlines and dealing with translation conflicts as in the PR that I have made seems to achieve?

**Comment by LoneWolfHT** [comment]
Making the formspec wider or just adding scrollbars would be best. I'll look into that

**Comment by src4026** [comment]
> Making the formspec wider or just adding scrollbars would be best. I'll look into that

I'll check the code once too. If I can do it then it would be less of a burden on you 👍

**Comment by LoneWolfHT** [comment]
#31

**Pull request closed without merging**
