### PR TITLE
Create "mod.conf" for 5.0.0+

### PR DESCRIPTION
**Pull request by Panquesito7**
Title says it all.

### CODE REVIEW

**Comment by ClobberXD** [comment]
Please also delete `depends.txt`

**Comment by Panquesito7** [comment]
@ClobberXD ping.

**Comment by ClobberXD** [comment]
I don't have write-access in this repository; ping @rubenwardy instead :P

**Comment by Panquesito7** [comment]
He was already pinged (by you).
Hope he looks at the PR, soon; thank you, anyway. 🙂

**Pull request merged**
